
version: 2

models:
  - name: active_faciities
    description: "nasa active site names only"
    columns:
      - name: status
        description: "status, active or null, but should be Active only for this table"
        tests:
          - not_null
          - accepted_values:
              values: ['Active']


