{{ config(materialized='view') }}

SELECT t1.MNEMONIC, t1.NAME, t2.LEARNING_OUTCOME
FROM ERD_COURSE_INFO t1
RIGHT JOIN (SELECT DISTINCT MNEMONIC, LEARNING_OUTCOME
FROM ERD_LEARNING_OUTCOMES
WHERE LEARNING_OUTCOME LIKE '%SQL%') t2 ON t1.MNEMONIC = t2.MNEMONIC
-- DO NOT USE ; in these sql files

