{{ config(materialized='view') }}

SELECT t1.MNEMONIC, t1.TERM, t1.INSTRUCTOR_FIRST_NAME, t1.INSTRUCTOR_LAST_NAME
FROM ERD_TEACHING_ASSIGNMENTS t1 LEFT JOIN
(SELECT MNEMONIC,TERM
       	FROM (SELECT DISTINCT MNEMONIC, TERM, COUNT(INSTRUCTOR_FIRST_NAME) AS No_INSTRUCTORS
        FROM ERD_TEACHING_ASSIGNMENTS
        GROUP BY MNEMONIC, TERM
       )
WHERE No_INSTRUCTORS > 1) t2 ON t1.MNEMONIC=t2.MNEMONIC AND t1.TERM=t2.TERM
WHERE t2.MNEMONIC IS NOT NULL 
-- DO NOT USE ; in these sql files

