{{ config(materialized='view') }}

SELECT TERM, INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME, INSTRUCTOR_NAME
FROM (SELECT CONCAT(INSTRUCTOR_FIRST_NAME, ' ',  INSTRUCTOR_LAST_NAME) as INSTRUCTOR_NAME, 
	TERM,INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME 
	FROM ERD_TEACHING_ASSIGNMENTS
)
WHERE TERM = 'FALL2021'
ORDER BY INSTRUCTOR_NAME
-- DO NOT USE ; in these sql files

