{{ config(materialized='view') }}

SELECT t1.MNEMONIC, t1.NAME
FROM ERD_COURSE_INFO t1
LEFT JOIN (SELECT DISTINCT MNEMONIC
FROM ERD_LEARNING_OUTCOMES
GROUP BY MNEMONIC) t2 ON t1.MNEMONIC = t2.MNEMONIC
WHERE t2.MNEMONIC IS NULL
-- DO NOT USE ; in these sql files

