{{ config(materialized='view') }}

SELECT MNEMONIC, TERM
FROM (SELECT DISTINCT MNEMONIC, TERM, COUNT(INSTRUCTOR_FIRST_NAME) AS No_INSTRUCTORS
        FROM ERD_TEACHING_ASSIGNMENTS
	GROUP BY MNEMONIC, TERM
)
WHERE No_INSTRUCTORS > 1
-- DO NOT USE ; in these sql files

