{{ config(materialized='view') }}

SELECT DISTINCT INSTRUCTOR_NAME, TERM,
COUNT(MNEMONIC) AS No_COURSES_TAUGHT
FROM (SELECT CONCAT(INSTRUCTOR_FIRST_NAME, ' ',  INSTRUCTOR_LAST_NAME) AS INSTRUCTOR_NAME,
        TERM,INSTRUCTOR_FIRST_NAME, INSTRUCTOR_LAST_NAME, MNEMONIC
        FROM ERD_TEACHING_ASSIGNMENTS
)
GROUP BY INSTRUCTOR_NAME, TERM 
ORDER BY TERM, INSTRUCTOR_NAME
-- DO NOT USE ; in these sql files

